-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS tickets
(
    id serial NOT NULL,
    subject character varying(255) NOT NULL,
    content character varying(1000) NOT NULL,
    html character varying(255),
    priority character varying(255),
    status character varying(255),
    project_id integer,
    user_id integer,
	settings_id integer UNIQUE,
    created_at date NOT NULL default now(),
    updated_at date,
    completed_at date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS settings
(
    id serial NOT NULL,
    lang character varying(255),
    slug character varying(255),
    value character varying(255),
    "default" character varying(255),
    created_at date NOT NULL default now(),
    updated_at date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id serial NOT NULL,
    content character varying(1000),
    user_id integer,
    ticket_id integer,
    created_at date NOT NULL default now(),
    updated_at date,
    html character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS teams
(
    id serial NOT NULL,
    name character varying(255) NOT NULL,
    location character varying(255),
    poc character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id serial NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    team_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS projects
(
    id serial,
    name character varying(255) NOT NULL,
    created_at date NOT NULL default now(),
    updated_at date NOT NULL,
    completed_at date NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE tickets
    ADD FOREIGN KEY (user_id)
    REFERENCES users (id)
    NOT VALID;


ALTER TABLE comments
    ADD FOREIGN KEY (user_id)
    REFERENCES users (id)
    NOT VALID;


ALTER TABLE comments
    ADD FOREIGN KEY (ticket_id)
    REFERENCES tickets (id)
    NOT VALID;


ALTER TABLE users
    ADD FOREIGN KEY (team_id)
    REFERENCES teams (id)
    NOT VALID;
	
ALTER TABLE tickets
	ADD FOREIGN KEY (settings_id)
	REFERENCES settings (id)
	NOT VALID;

ALTER TABLE tickets
	ADD FOREIGN KEY (project_id)
	REFERENCES projects (id)
	NOT VALID;
	
END;