-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.tickets
(
    id serial NOT NULL,
    subject character varying(255) NOT NULL,
    content character varying(1000) NOT NULL,
    html character varying(255),
    priority character varying(255),
    status character varying(255),
    project_id integer,
    user_id integer,
	settings_id integer UNIQUE,
    created_at date NOT NULL default now(),
    updated_at date,
    completed_at date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.settings
(
    id serial NOT NULL,
    lang character varying(255),
    slug character varying(255),
    value character varying(255),
    "default" character varying(255),
    created_at date NOT NULL default now(),
    updated_at date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id serial NOT NULL,
    content character varying(1000),
    user_id integer,
    ticket_id integer,
    created_at date NOT NULL default now(),
    updated_at date,
    html character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.teams
(
    id serial NOT NULL,
    name character varying(255) NOT NULL,
    location character varying(255),
    poc character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    team_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id serial,
    name character varying(255) NOT NULL,
    created_at date NOT NULL default now(),
    updated_at date NOT NULL,
    completed_at date NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE public.tickets
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.comments
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.comments
    ADD FOREIGN KEY (ticket_id)
    REFERENCES public.tickets (id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (team_id)
    REFERENCES public.teams (id)
    NOT VALID;
	
ALTER TABLE public.tickets
	ADD FOREIGN KEY (settings_id)
	REFERENCES public.settings (id)
	NOT VALID;

ALTER TABLE public.tickets
	ADD FOREIGN KEY (project_id)
	REFERENCES public.projects (id)
	NOT VALID;
	
END;